### ISSUE TITLE
changing the repo name to `js-cluster-api`

### ISSUE THREAD

**Issue by vasa-develop** [cluster-labs/ipfs-cluster-api#10]
Are we expecting other language implementations for this API in the future?
If yes, then I think it's better to name this repo `js-cluster-api`. Or if there are no such plans, then let's leave it.

Even if we change the repo name we will still keep the npm module name: `ipfs-cluster-api`

@hsanjuan what are your thoughts?

**Comment by hsanjuan** [comment]
Then let's change the repo name and keep the module name

**Comment by vasa-develop** [comment]
@hsanjuan 
I don't seem to have permission. Can you do that?
